# Generated by Django 3.2.7 on 2021-09-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=15, verbose_name='Cpf')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Dado',
                'verbose_name_plural': 'Dados',
            },
        ),
    ]
